# .github/workflows/ci.yml

name: CI/CD Pipeline for ML Model Training

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  testing: #change name
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone private repository
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: git clone https://$PAT_TOKEN@github.com/PJATK-ASI-2024/Lab2---Obr-bka-danych.git

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: run data generation
        run: python Lab2---Obr-bka-danych/generator_danych.py -s 21147
  
      - name: cat data
        run: cat data_student_21147.csv