# .github/workflows/ci.yml

name: CI/CD Pipeline for ML Model Training

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  data-processing: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone private repository
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git clone https://$PAT_TOKEN@github.com/PJATK-ASI-2024/Lab2---Obr-bka-danych.git

      - name: Install data generation dependencies
        run: pip install -r Lab2---Obr-bka-danych/requirements.txt

      - name: run data generation
        run: python Lab2---Obr-bka-danych/generator_danych.py -s 21147

      - name: install data processing dependencies
        run: pip install -r requirements.txt

      - name: run python script
        env: 
          GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python data_processing.py

      - name: read report.txt
        run: cat report.txt

      - name: read log.txt
        run: cat log.txt